# Generated by Django 4.2.11 on 2024-03-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(max_length=15)),
                ('Event', models.CharField(max_length=55)),
                ('Teammate1', models.CharField(blank=True, max_length=55, null=True)),
                ('Teammate2', models.CharField(blank=True, max_length=55, null=True)),
                ('Teammate3', models.CharField(blank=True, max_length=55, null=True)),
                ('Teammate4', models.CharField(blank=True, max_length=55, null=True)),
                ('Teammate5', models.CharField(blank=True, max_length=55, null=True)),
                ('Teammate6', models.CharField(blank=True, max_length=55, null=True)),
                ('Teammate7', models.CharField(blank=True, max_length=55, null=True)),
                ('Teammate8', models.CharField(blank=True, max_length=55, null=True)),
                ('Teammate9', models.CharField(blank=True, max_length=55, null=True)),
                ('Teammate10', models.CharField(blank=True, max_length=55, null=True)),
                ('College', models.CharField(max_length=155)),
                ('Degree', models.CharField(max_length=25)),
                ('Year', models.CharField(max_length=10)),
                ('Registered', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
            ],
        ),
    ]
