# Generated by Django 4.2.11 on 2024-03-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Degree',
            field=models.CharField(max_length=55),
        ),
    ]
