# Generated by Django 4.2.11 on 2024-03-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_participant_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Year',
            field=models.CharField(max_length=25),
        ),
    ]
