# Generated by Django 5.0.3 on 2024-03-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_participant_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Registered',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3),
        ),
    ]
