# Generated by Django 4.2.11 on 2024-03-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_participant_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Registered',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('SPOT', 'SPOT')], default='NO', max_length=5),
        ),
    ]
