# Generated by Django 4.2.11 on 2024-03-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_participant_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='Transaction_ID',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
